services:
  master:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - .:/locust
    command: -f /locust/locustfile.py --master --host http://backend:8080
    networks:
      - default
      - hikikomori

  worker:
    build: .
    volumes:
      - .:/locust
    command: -f /locust/locustfile.py --worker --master-host master
    depends_on:
      - master
    deploy:
      replicas: 2
    networks:
      - default
      - hikikomori

networks:
  hikikomori:
    external: true
    name: hikikomori_default
